# Try to find allegro 5
#
#  ALLEGRO5_NATIVE_DIALOGS_FOUND - system has allegro5
#  ALLEGRO5_NATIVE_DIALOGS_INCLUDE_DIRS - the allrgo5 include directory
#  ALLEGRO5_NATIVE_DIALOGS_LIBRARIES - Link these to use allegro5
#

FIND_PATH(ALLEGRO5_NATIVE_DIALOGS_INCLUDE_DIR allegro_native_dialog.h
  HINTS
  $ENV{LUA_DIR}
  PATH_SUFFIXES include/allegro5 include/allegro include
  PATHS
  ~/Library/Frameworks
  /Library/Frameworks
  /usr/local
  /usr
  /sw
  /opt/local
  /opt/csw
  /opt
)

FIND_LIBRARY(ALLEGRO5_NATIVE_DIALOGS_LIBRARY
  NAMES allegro_dialog
  HINTS
  $ENV{ALLEGRO5_DIR}
  PATH_SUFFIXES lib64 lib
  PATHS
  ~/Library/Frameworks
  /Library/Frameworks
  /usr/local
  /usr
  /sw
  /opt/local
  /opt/csw
  /opt
)

MESSAGE(STATUS "${ALLEGRO5_NATIVE_DIALOGS_LIBRARY}")

IF(ALLEGRO5_NATIVE_DIALOGS_LIBRARY)
  SET(ALLEGRO5_NATIVE_DIALOGS_LIBRARIES "${ALLEGRO5_NATIVE_DIALOGS_LIBRARY}" CACHE STRING "Allegro5 Native Dialogs Libraries")
  SET(ALLEGRO5_NATIVE_DIALOGS_INCLUDE_DIRS "${ALLEGRO5_NATIVE_DIALOGS_INCLUDE_DIR}" CACHE STRING "Allegro5 Native Dialogs Include Dirs")
  SET(ALLEGRO5_NATIVE_DIALOGS_FOUND TRUE)
ENDIF(ALLEGRO5_NATIVE_DIALOGS_LIBRARY)

MARK_AS_ADVANCED(ALLEGRO5_NATIVE_DIALOGS_INCLUDE_DIR ALLEGRO5_NATIVE_DIALOGS_INCLUDE_DIRS ALLEGRO5_NATIVE_DIALOGS_LIBRARIES ALLEGRO5_NATIVE_DIALOGS_LIBRARY)
